src/WolfeReiter.Identity.DualStack/Controllers/DiagnosticsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MimeKit;
using WolfeReiter.Identity.DualStack.Models;

namespace WolfeReiter.Identity.DualStack.Controllers
{

    [Authorize]
    public class DiagnosticsController : Controller
    {
        private readonly ILogger<DiagnosticsController> _logger;

        readonly SmtpClientService SmtpClient;

        public DiagnosticsController(ILogger<DiagnosticsController> logger, SmtpClientService smtpClient)
        {
            _logger = logger;
            SmtpClient = smtpClient;
        }

        public IActionResult Index()
        {
            return View();
        }

        //test that SMTP is configured
        //https://localhost:5001/Diagnostics/Mail/youremail@domain.com
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Mail(string id)
        {
            string email = id;

            var message = new MimeMessage();
            var builder = new BodyBuilder
            {
                TextBody = "Hello. It works."
            };
            message.Body = builder.ToMessageBody();
            message.Subject = "Test email";
            message.To.Add(new MailboxAddress(name: null, address: email));
            message.From.Add(SmtpClient.SystemFromAddress);
            try
            {
                await SmtpClient.SendMessageAsync(message);
                return Content("OK. Check your inbox.");
            }
            catch (Exception ex)
            {
                return Content($"{ex.Message}\r\n\r\n{ex.StackTrace}");
            }
        }

        [Authorize(Roles = "85de0d3fb8f54ebb94e9cc6747545271")] //fake role
        public IActionResult Denied()
        {
            return Content("You should not see this message.");
        }
    }
}

src/WolfeReiter.Identity.DualStack/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <title>@ViewData["Title"] - WolfeReiter.Identity.DualStack</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WolfeReiter.Identity.DualStack</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav text-right">
                        @if (User.Identity?.IsAuthenticated ?? false)
                        {
                            //instead of testing roles, test policy
                            //@if (User.IsInRole(Roles.Administrator))
                            @if ((await AuthorizationService.AuthorizeAsync(User, Policies.Administration)).Succeeded)
                            {
                            <li class="nav-item dropdown text-right">
                                <a class="nav-link text-dark dropdown-toggle" href="#" id="navbarAdminMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Administration
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarAdminMenuLink">
                                    <a class="dropdown-item" asp-controller="Account" asp-action="New">Create New Account</a>
                                    <a class="dropdown-item" asp-controller="Account" asp-action="List">Manage User Accounts</a>
                                </div>
                            </li>
                            }
                        <li class="nav-item dropdown text-right">
                            <a class="nav-link text-dark dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                @User.Identity.Name
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" asp-controller="Home" asp-action="Index">Home</a>
                                <a class="dropdown-item" asp-controller="Home" asp-action="Index">Privacy</a>
                                <a class="dropdown-item" asp-controller="Diagnostics" asp-action="Index">Diagnostics - Claims</a>
                                <a class="dropdown-item" asp-controller="Diagnostics" asp-action="Denied">Diagnostics - Denied</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-controller="Account" asp-action="SignOut">Log out</a>
                            </div>
                        </li>
                        }
                        else {
                            <li class="nav-item">
                                <a class="nav-link text-dark text-right" asp-controller="Account" asp-action="SignInMethod">Log in</a>
                        </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - WolfeReiter.Identity.DualStack - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>